Fix compiler error due to missing assert.h include
Error was:

mednafen/ngp/interrupt.cpp: In function ‘void set_interrupt(uint8_t, bool)’:
mednafen/ngp/interrupt.cpp:73:4: error: ‘assert’ was not declared in this scope
    assert(index < 24);
    ^~~~~~